name:                open-redactle
version:             0.1.0.0
github:              "aliics/open-redactle"
license:             BSD-3-Clause
author:              "Aliics"
maintainer:          "Aliics@hotmail.com"
copyright:           "2024 Aliics"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aliics/open-redactle#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - aeson == 2.1.2.1
    - text == 2.0.2
    - bytestring == 0.11.5.3
    - http-client == 0.7.17
    - http-client-tls == 0.3.6.3

executables:
  open-redactle-article-fetcher-exe:
    main: Main.hs
    source-dirs: app/article-fetcher
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - open-redactle
  open-redactle-server-exe:
    main:                Main.hs
    source-dirs:         app/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-redactle

tests:
  open-redactle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-redactle
