name:                 open-redactle
version:              0.1.0.0
visibility:           public
id:                   open-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3
key:                  open-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3
license:              BSD-3-Clause
copyright:            2024 Aliics
maintainer:           Aliics@hotmail.com
author:               Aliics
homepage:             https://github.com/aliics/open-redactle#readme
description:
    Please see the README on GitHub at <https://github.com/aliics/open-redactle#readme>

abi:                  1ddda3dc4e29e205232cc64e5b053ea9
exposed:              True
exposed-modules:      Data.Wikipedia.Article Network.Wikipedia.Constants
hidden-modules:       Paths_open_redactle
import-dirs:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/lib/x86_64-linux-ghc-9.6.5/open-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3

library-dirs:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/lib/x86_64-linux-ghc-9.6.5/open-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3

library-dirs-static:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/lib/x86_64-linux-ghc-9.6.5/open-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3

dynamic-library-dirs:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/lib/x86_64-linux-ghc-9.6.5

data-dir:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/share/x86_64-linux-ghc-9.6.5/open-redactle-0.1.0.0

hs-libraries:         HSopen-redactle-0.1.0.0-4MObrkgI7czFfhPmJwYKc3
depends:
    aeson-2.1.2.1-F3hDGK91Wx42rTliAGkUq base-4.18.2.1 text-2.0.2

haddock-interfaces:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/doc/open-redactle-0.1.0.0/open-redactle.haddock

haddock-html:
    /home/aliics/devel/open-redactle/.stack-work/install/x86_64-linux-tinfo6/82bebf1dc2072c10e5d722e3198bc75517d79d5c515ff5d84ea46477434ab1f6/9.6.5/doc/open-redactle-0.1.0.0
